url: ''
title: ZosKia Cultus Workshop
email: contato@babalontherion.studio
author: Pedro Pietro
description: >
  You can edit this line in _config.yml. It will appear in your document  head
  meta (for Google search results) and in your feed.xml site  description.
copyright: Copyright &copy; 2018 Babalon & Therion Studio All Rights Reserved.
credits: Produção de Babalon & Therion Studio
plugins:
  - jekyll-seo-tag
markdown: kramdown
permalink: pretty
social:
  - title: twitter
    url: 'https://twitter.com/babalontherion'
  - title: facebook
    url: 'https://www.facebook.com/BabalonTherionStudio/'
  - title: instagram
    url: 'https://www.instagram.com/procuradordegatos/'
baseurl: ''
